// This file is generated by scripts/generate-seo.mjs. Do not edit by hand.
export type HomeBlogUpdate = {
  claimId: string;
  side: "hommes" | "femmes";
  claimTitle: string;
  claimMetric: string;
  blogTitle: string;
  blogUrl: string;
  date: string;
  updatedAt: string;
};

export const homeBlogUpdates = [
  {
    "claimId": "femmes-personnel-sante-ecart-remuneration-region-europe-2026",
    "side": "femmes",
    "claimTitle": "Rémunération moyenne plus faible pour les femmes du secteur de la santé et de l'aide sociale",
    "claimMetric": "−19 %/h · −28 %/mois",
    "blogTitle": "Santé et aide sociale : les femmes gagnent moins en moyenne dans la région européenne de l'OMS",
    "blogUrl": "/blog/2026-09-18-ecart-remuneration-personnel-sante-femmes-hommes-europe/",
    "date": "2026-09-18",
    "updatedAt": "2026-09-18T18:33:00.000Z"
  },
  {
    "claimId": "femmes-limitations-activite-union-europeenne-2025",
    "side": "femmes",
    "claimTitle": "Limitations d'activité durables plus souvent déclarées par les femmes dans l'UE",
    "claimMetric": "26,5 % vs 21,8 %",
    "blogTitle": "Limitations d'activité : un écart déclaré entre femmes et hommes dans l'Union européenne",
    "blogUrl": "/blog/2026-09-17-limitations-activite-femmes-hommes-union-europeenne-2025/",
    "date": "2026-09-17",
    "updatedAt": "2026-09-17T19:22:00.000Z"
  },
  {
    "claimId": "femmes-medecins-liberaux-revenu-france-2021",
    "side": "femmes",
    "claimTitle": "Revenu d'activité moyen plus faible pour les femmes médecins libérales",
    "claimMetric": "90 000 € vs 148 000 €",
    "blogTitle": "Médecins libéraux : des revenus moyens différents selon le sexe et des effets de structure à distinguer",
    "blogUrl": "/blog/2026-09-17-revenus-medecins-liberaux-femmes-hommes-france/",
    "date": "2026-09-17",
    "updatedAt": "2026-09-17T14:54:00.000Z"
  },
  {
    "claimId": "femmes-troubles-anxieux-monde-2021",
    "side": "femmes",
    "claimTitle": "Femmes majoritaires parmi les personnes vivant avec un trouble anxieux",
    "claimMetric": "63,3 %",
    "blogTitle": "Troubles anxieux : les femmes sont davantage représentées parmi les personnes touchées",
    "blogUrl": "/blog/2026-09-16-troubles-anxieux-femmes-hommes-monde/",
    "date": "2026-09-16",
    "updatedAt": "2026-09-16T06:43:05.000Z"
  },
  {
    "claimId": "hommes-contraintes-physiques-travail-france-2024",
    "side": "hommes",
    "claimTitle": "Contraintes physiques au travail plus fréquentes chez les hommes",
    "claimMetric": "+8 pts",
    "blogTitle": "Conditions de travail : les asymétries femmes-hommes changent selon le risque observé",
    "blogUrl": "/blog/2026-09-14-conditions-travail-risques-femmes-hommes-france/",
    "date": "2026-09-14",
    "updatedAt": "2026-09-14T07:21:38.195Z"
  },
  {
    "claimId": "femmes-violences-sexuelles-transports-hce-2025",
    "side": "femmes",
    "claimTitle": "Femmes très majoritaires parmi les victimes de violences sexuelles dans les transports",
    "claimMetric": "91 % F (2024)",
    "blogTitle": "Transports en commun : baisse globale des atteintes enregistrées, mais violences sexuelles en hausse",
    "blogUrl": "/blog/2026-09-11-transports-violences-enregistrees-femmes-hommes-france-2025/",
    "date": "2026-09-11",
    "updatedAt": "2026-09-11T18:45:55.316Z"
  },
  {
    "claimId": "hommes-sans-abrisme",
    "side": "hommes",
    "claimTitle": "Hommes majoritaires dans 31 des 33 pays renseignés par l'OCDE",
    "claimMetric": "31 pays sur 33",
    "blogTitle": "Sans-abrisme en Angleterre : les hommes dominent les comptes de rue, mais l'asymétrie dépend du périmètre mesuré",
    "blogUrl": "/blog/2026-07-19-sans-abrisme-angleterre-rue-hommes-majoritaires-perimetre/",
    "date": "2026-07-19",
    "updatedAt": "2026-09-10T18:41:12.021Z"
  },
  {
    "claimId": "hommes-suicide",
    "side": "hommes",
    "claimTitle": "Décès par suicide : surmortalité masculine en France et dans l'UE",
    "claimMetric": "75 % FR · 76,4 % UE",
    "blogTitle": "Suicide et gestes auto-infligés : deux asymétries de sexe à lire séparément en 2026",
    "blogUrl": "/blog/2026-06-25-suicide-gestes-auto-infliges-asymetries-sexe/",
    "date": "2026-06-25",
    "updatedAt": "2026-09-09T18:31:51.219Z"
  },
  {
    "claimId": "hommes-suicide-monde",
    "side": "hommes",
    "claimTitle": "Hommes beaucoup plus exposés à la mort par suicide",
    "claimMetric": ">2x",
    "blogTitle": "Suicide et gestes auto-infligés : deux asymétries de sexe à lire séparément en 2026",
    "blogUrl": "/blog/2026-06-25-suicide-gestes-auto-infliges-asymetries-sexe/",
    "date": "2026-06-25",
    "updatedAt": "2026-09-09T18:31:51.219Z"
  },
  {
    "claimId": "femmes-ingenierie",
    "side": "femmes",
    "claimTitle": "Femmes moins présentes dans l'ingénierie malgré une réussite scolaire élevée",
    "claimMetric": "24 %",
    "blogTitle": "PISA 2025 : en France, 32 points d’avance pour les filles en lecture, 13 pour les garçons en mathématiques",
    "blogUrl": "/blog/2026-09-08-pisa-2025-lecture-mathematiques-filles-garcons/",
    "date": "2026-09-08",
    "updatedAt": "2026-09-08T18:34:46.403Z"
  },
  {
    "claimId": "hommes-decrochage-garcons-monde",
    "side": "hommes",
    "claimTitle": "Garçons plus nombreux hors de l'école dans l'estimation mondiale récente",
    "claimMetric": "140 M vs 133 M",
    "blogTitle": "PISA 2025 : en France, 32 points d’avance pour les filles en lecture, 13 pour les garçons en mathématiques",
    "blogUrl": "/blog/2026-09-08-pisa-2025-lecture-mathematiques-filles-garcons/",
    "date": "2026-09-08",
    "updatedAt": "2026-09-08T18:34:46.403Z"
  },
  {
    "claimId": "hommes-sorties-precoces",
    "side": "hommes",
    "claimTitle": "Garçons plus touchés par les sorties précoces du système scolaire",
    "claimMetric": "9,5 % vs 5,6 %",
    "blogTitle": "Sorties précoces d'études : les jeunes hommes restent plus exposés en Europe",
    "blogUrl": "/blog/2026-06-30-sorties-precoces-jeunes-hommes-europe-france/",
    "date": "2026-06-30",
    "updatedAt": "2026-09-07T19:03:37.000Z"
  },
  {
    "claimId": "femmes-soin-non-remunere-emploi",
    "side": "femmes",
    "claimTitle": "Femmes tenues hors de l'emploi par le soin non rémunéré",
    "claimMetric": "708 M",
    "blogTitle": "Chômage en 2026 : taux féminin plus élevé dans l’UE, taux masculin légèrement plus élevé en France",
    "blogUrl": "/blog/2026-09-05-chomage-femmes-hommes-ue-france-2026/",
    "date": "2026-09-05",
    "updatedAt": "2026-09-05T18:42:00.000Z"
  },
  {
    "claimId": "femmes-temps-partiel",
    "side": "femmes",
    "claimTitle": "Temps partiel plus fréquent chez les femmes, lecture ambivalente",
    "claimMetric": "26,8 % vs 8,7 %",
    "blogTitle": "Chômage en 2026 : taux féminin plus élevé dans l’UE, taux masculin légèrement plus élevé en France",
    "blogUrl": "/blog/2026-09-05-chomage-femmes-hommes-ue-france-2026/",
    "date": "2026-09-05",
    "updatedAt": "2026-09-05T18:42:00.000Z"
  },
  {
    "claimId": "hommes-part-auteurs-violences-sexuelles-perception",
    "side": "hommes",
    "claimTitle": "Auteurs masculins majoritaires ne signifie pas hommes majoritairement auteurs",
    "claimMetric": "99 % ≠ 99 %",
    "blogTitle": "Violences sexuelles : distinguer sexe des auteurs déclarés, part des hommes, classements et fausses plaintes",
    "blogUrl": "/blog/2026-08-11-violences-sexuelles-auteurs-classements-fausses-plaintes-statistiques/",
    "date": "2026-08-11",
    "updatedAt": "2026-08-11T17:40:00.000Z"
  },
  {
    "claimId": "hommes-reconnaissance-viol-lois-europe",
    "side": "hommes",
    "claimTitle": "Certaines lois européennes ne reconnaissent pas pleinement les hommes comme victimes de viol",
    "claimMetric": "4 pays cités",
    "blogTitle": "Violences sexuelles : distinguer sexe des auteurs déclarés, part des hommes, classements et fausses plaintes",
    "blogUrl": "/blog/2026-08-11-violences-sexuelles-auteurs-classements-fausses-plaintes-statistiques/",
    "date": "2026-08-11",
    "updatedAt": "2026-08-11T17:40:00.000Z"
  },
  {
    "claimId": "hommes-femmes-peurs-consentement-sexuel",
    "side": "hommes",
    "claimTitle": "Classement, fausse plainte et culpabilité : trois notions distinctes",
    "claimMetric": "69 % ≠ faux",
    "blogTitle": "Violences sexuelles : distinguer sexe des auteurs déclarés, part des hommes, classements et fausses plaintes",
    "blogUrl": "/blog/2026-08-11-violences-sexuelles-auteurs-classements-fausses-plaintes-statistiques/",
    "date": "2026-08-11",
    "updatedAt": "2026-08-11T17:40:00.000Z"
  },
  {
    "claimId": "hommes-agresseurs-declares-violences-sexuelles-femmes-france",
    "side": "hommes",
    "claimTitle": "Hommes quasi exclusifs parmi les agresseurs déclarés par les femmes victimes de violences sexuelles",
    "claimMetric": "99 %",
    "blogTitle": "Violences sexuelles : distinguer sexe des auteurs déclarés, part des hommes, classements et fausses plaintes",
    "blogUrl": "/blog/2026-08-11-violences-sexuelles-auteurs-classements-fausses-plaintes-statistiques/",
    "date": "2026-08-11",
    "updatedAt": "2026-08-11T17:40:00.000Z"
  },
  {
    "claimId": "hommes-attribution-laxisme-justice-violences-sexuelles",
    "side": "hommes",
    "claimTitle": "Violences sexuelles : la justice française n'est pas un corps exclusivement masculin",
    "claimMetric": "70 % / 63 %",
    "blogTitle": "Violences sexuelles : distinguer sexe des auteurs déclarés, part des hommes, classements et fausses plaintes",
    "blogUrl": "/blog/2026-08-11-violences-sexuelles-auteurs-classements-fausses-plaintes-statistiques/",
    "date": "2026-08-11",
    "updatedAt": "2026-08-11T17:40:00.000Z"
  },
  {
    "claimId": "femmes-arret-cardiaque-defibrillation-temoins",
    "side": "femmes",
    "claimTitle": "Femmes moins susceptibles de recevoir un défibrillateur posé par un témoin",
    "claimMetric": "OR 0,79",
    "blogTitle": "Arrêt cardiaque : les femmes reçoivent moins souvent certains gestes de témoins, mais la peur des plaintes reste mal mesurée",
    "blogUrl": "/blog/2026-08-11-arret-cardiaque-femmes-rcp-defibrillateur-peur-contact/",
    "date": "2026-08-11",
    "updatedAt": "2026-08-11T17:35:00.000Z"
  },
  {
    "claimId": "femmes-violences-conjugales",
    "side": "femmes",
    "claimTitle": "Femmes majoritaires parmi les victimes conjugales enregistrées",
    "claimMetric": "84 %",
    "blogTitle": "Violences enregistrées en France : les hommes sont majoritaires hors famille, les femmes dans la famille",
    "blogUrl": "/blog/2026-08-11-violences-enregistrees-hommes-hors-famille-femmes-dans-famille/",
    "date": "2026-08-11",
    "updatedAt": "2026-08-11T17:30:00.000Z"
  },
  {
    "claimId": "hommes-mis-en-cause-violences-conjugales-france",
    "side": "hommes",
    "claimTitle": "Hommes majoritaires parmi les mis en cause pour violences conjugales",
    "claimMetric": "85 %",
    "blogTitle": "Violences enregistrées en France : les hommes sont majoritaires hors famille, les femmes dans la famille",
    "blogUrl": "/blog/2026-08-11-violences-enregistrees-hommes-hors-famille-femmes-dans-famille/",
    "date": "2026-08-11",
    "updatedAt": "2026-08-11T17:30:00.000Z"
  },
  {
    "claimId": "hommes-violences-physiques-hors-famille-france-2025",
    "side": "hommes",
    "claimTitle": "Violences enregistrées : hommes majoritaires hors famille, femmes dans la famille",
    "claimMetric": "68 % H / 73 % F",
    "blogTitle": "Violences enregistrées en France : les hommes sont majoritaires hors famille, les femmes dans la famille",
    "blogUrl": "/blog/2026-08-11-violences-enregistrees-hommes-hors-famille-femmes-dans-famille/",
    "date": "2026-08-11",
    "updatedAt": "2026-08-11T17:30:00.000Z"
  },
  {
    "claimId": "hommes-sexisme-hostile-hce-2025",
    "side": "hommes",
    "claimTitle": "Adhésion au sexisme hostile envers les femmes plus fréquente chez les hommes",
    "claimMetric": "23 % vs 12 %",
    "blogTitle": "Féminisme, masculinisme et leurs oppositions : quatre axes de vocabulaire à distinguer",
    "blogUrl": "/blog/2026-06-25-masculinisme-feminisme-vocabulaire-asymetrie/",
    "date": "2026-06-25",
    "updatedAt": "2026-08-11T16:30:00.000Z"
  },
  {
    "claimId": "hommes-pensions-alimentaires",
    "side": "hommes",
    "claimTitle": "Dans les décisions étudiées en 2012, le père était débiteur dans 97 % des pensions fixées",
    "claimMetric": "97 %",
    "blogTitle": "Féminisme, masculinisme et leurs oppositions : quatre axes de vocabulaire à distinguer",
    "blogUrl": "/blog/2026-06-25-masculinisme-feminisme-vocabulaire-asymetrie/",
    "date": "2026-06-25",
    "updatedAt": "2026-08-11T16:30:00.000Z"
  },
  {
    "claimId": "hommes-residence-alternee",
    "side": "hommes",
    "claimTitle": "En 2023, 14 % des enfants de parents séparés vivent à temps égal chez chacun",
    "claimMetric": "14 %",
    "blogTitle": "Féminisme, masculinisme et leurs oppositions : quatre axes de vocabulaire à distinguer",
    "blogUrl": "/blog/2026-06-25-masculinisme-feminisme-vocabulaire-asymetrie/",
    "date": "2026-06-25",
    "updatedAt": "2026-08-11T16:30:00.000Z"
  },
  {
    "claimId": "hommes-mortalite-travail-monde",
    "side": "hommes",
    "claimTitle": "Hommes davantage exposés à la mortalité liée au travail",
    "claimMetric": "51,4 vs 17,2",
    "blogTitle": "Féminisme, masculinisme et leurs oppositions : quatre axes de vocabulaire à distinguer",
    "blogUrl": "/blog/2026-06-25-masculinisme-feminisme-vocabulaire-asymetrie/",
    "date": "2026-06-25",
    "updatedAt": "2026-08-11T16:30:00.000Z"
  },
  {
    "claimId": "hommes-bourses-stem-reservees-femmes",
    "side": "hommes",
    "claimTitle": "Hommes exclus de certaines bourses STEM réservées aux femmes",
    "claimMetric": "15 000 €",
    "blogTitle": "Féminisme, masculinisme et leurs oppositions : quatre axes de vocabulaire à distinguer",
    "blogUrl": "/blog/2026-06-25-masculinisme-feminisme-vocabulaire-asymetrie/",
    "date": "2026-06-25",
    "updatedAt": "2026-08-11T16:30:00.000Z"
  },
  {
    "claimId": "hommes-vocabulaire-masculinisme-pejoratif",
    "side": "hommes",
    "claimTitle": "Masculinisme : définition Isora et usages péjoratifs des sources",
    "claimMetric": "4 axes",
    "blogTitle": "Féminisme, masculinisme et leurs oppositions : quatre axes de vocabulaire à distinguer",
    "blogUrl": "/blog/2026-06-25-masculinisme-feminisme-vocabulaire-asymetrie/",
    "date": "2026-06-25",
    "updatedAt": "2026-08-11T16:30:00.000Z"
  },
  {
    "claimId": "hommes-femmes-sexisme-paternaliste-hce-2025",
    "side": "hommes",
    "claimTitle": "Sexisme paternaliste mesuré chez les deux sexes, plus souvent chez les hommes",
    "claimMetric": "27 % vs 18 %",
    "blogTitle": "Féminisme, masculinisme et leurs oppositions : quatre axes de vocabulaire à distinguer",
    "blogUrl": "/blog/2026-06-25-masculinisme-feminisme-vocabulaire-asymetrie/",
    "date": "2026-06-25",
    "updatedAt": "2026-08-11T16:30:00.000Z"
  },
  {
    "claimId": "femmes-separation-niveau-vie",
    "side": "femmes",
    "claimTitle": "Niveau de vie des femmes plus touché après séparation",
    "claimMetric": "-17 % vs -7 %",
    "blogTitle": "Monoparentalité : en Europe, les foyers avec enfants à un seul adulte restent très majoritairement féminins",
    "blogUrl": "/blog/2026-07-15-monoparentalite-europe-femmes-precarite-france/",
    "date": "2026-07-15",
    "updatedAt": "2026-07-15T06:30:00.000Z"
  },
  {
    "claimId": "hommes-ukraine-restrictions-sortie-2022-2025",
    "side": "hommes",
    "claimTitle": "Hommes ukrainiens d'âge militaire limités à la frontière",
    "claimMetric": "18-60 ans",
    "blogTitle": "Protection temporaire des déplacés d'Ukraine : femmes et enfants restent majoritaires dans l'UE",
    "blogUrl": "/blog/2026-07-13-protection-temporaire-ukraine-femmes-enfants-hommes-ue/",
    "date": "2026-07-13",
    "updatedAt": "2026-07-13T06:30:00.000Z"
  },
  {
    "claimId": "femmes-menopause-soins",
    "side": "femmes",
    "claimTitle": "Information et accès aux soins liés à la ménopause encore insuffisants",
    "claimMetric": "accès inégal",
    "blogTitle": "Dépistage des cancers : des parcours de prévention différents pour les femmes et les hommes en France",
    "blogUrl": "/blog/2026-07-08-depistage-cancers-prevention-femmes-hommes-france/",
    "date": "2026-07-08",
    "updatedAt": "2026-07-08T06:30:00.000Z"
  },
  {
    "claimId": "femmes-ecart-salaire",
    "side": "femmes",
    "claimTitle": "Salaire inférieur pour une femme à profil comparable à un homme",
    "claimMetric": "3,0-4,8 %",
    "blogTitle": "Écart de salaire : ce que mesurent les chiffres récents de l'UE, de la France et de l'OCDE",
    "blogUrl": "/blog/2026-07-07-ecart-salaire-ue-france-ce-que-mesurent-les-chiffres/",
    "date": "2026-07-07",
    "updatedAt": "2026-07-07T06:30:00.000Z"
  },
  {
    "claimId": "femmes-feminicides-monde-2024",
    "side": "femmes",
    "claimTitle": "Femmes et filles tuées par des proches ou partenaires",
    "claimMetric": "50 000",
    "blogTitle": "Homicides : les hommes restent majoritaires au total, mais les femmes le sont davantage dans la sphère conjugale et familiale",
    "blogUrl": "/blog/2026-07-06-homicides-hommes-majoritaires-total-femmes-sphere-conjugale/",
    "date": "2026-07-06",
    "updatedAt": "2026-07-06T06:30:00.000Z"
  },
  {
    "claimId": "femmes-violences-physiques-sexuelles-monde",
    "side": "femmes",
    "claimTitle": "Femmes exposées aux violences conjugales physiques ou sexuelles",
    "claimMetric": "1 sur 3",
    "blogTitle": "Homicides : les hommes restent majoritaires au total, mais les femmes le sont davantage dans la sphère conjugale et familiale",
    "blogUrl": "/blog/2026-07-06-homicides-hommes-majoritaires-total-femmes-sphere-conjugale/",
    "date": "2026-07-06",
    "updatedAt": "2026-07-06T06:30:00.000Z"
  },
  {
    "claimId": "hommes-victimes-homicide-monde",
    "side": "hommes",
    "claimTitle": "Hommes majoritaires parmi les victimes d'homicide",
    "claimMetric": "80 %",
    "blogTitle": "Homicides : les hommes restent majoritaires au total, mais les femmes le sont davantage dans la sphère conjugale et familiale",
    "blogUrl": "/blog/2026-07-06-homicides-hommes-majoritaires-total-femmes-sphere-conjugale/",
    "date": "2026-07-06",
    "updatedAt": "2026-07-06T06:30:00.000Z"
  },
  {
    "claimId": "hommes-age-retraite-differencie-ocde",
    "side": "hommes",
    "claimTitle": "Âge normal de retraite encore plus élevé pour les hommes dans certains pays",
    "claimMetric": "64,7 vs 63,9 ans",
    "blogTitle": "Retraites : les écarts de pension se réduisent, mais les femmes âgées restent plus exposées à la pauvreté",
    "blogUrl": "/blog/2026-07-05-retraites-ecart-pension-pauvrete-femmes-hommes-france-ue-ocde/",
    "date": "2026-07-05",
    "updatedAt": "2026-07-05T07:30:00.000Z"
  },
  {
    "claimId": "femmes-charge-domestique-soin",
    "side": "femmes",
    "claimTitle": "Femmes assumant beaucoup plus de soin non rémunéré",
    "claimMetric": "2,5x",
    "blogTitle": "Parentalité : l'emploi baisse surtout pour les mères, tandis que les pères gagnent du temps parental sans rattraper tout l'écart",
    "blogUrl": "/blog/2026-07-03-parentalite-emploi-meres-peres-enfants-france-ue-ocde/",
    "date": "2026-07-03",
    "updatedAt": "2026-07-03T18:30:00.000Z"
  },
  {
    "claimId": "hommes-conge-paternite-ocde",
    "side": "hommes",
    "claimTitle": "Pères limités par un congé paternité payé très court",
    "claimMetric": "2,4 sem.",
    "blogTitle": "Parentalité : l'emploi baisse surtout pour les mères, tandis que les pères gagnent du temps parental sans rattraper tout l'écart",
    "blogUrl": "/blog/2026-07-03-parentalite-emploi-meres-peres-enfants-france-ue-ocde/",
    "date": "2026-07-03",
    "updatedAt": "2026-07-03T18:30:00.000Z"
  },
  {
    "claimId": "hommes-accidents-route-monde",
    "side": "hommes",
    "claimTitle": "Hommes beaucoup plus exposés à la mortalité routière",
    "claimMetric": "3x",
    "blogTitle": "Sécurité routière : les hommes restent très majoritaires parmi les morts sur la route en France comme dans l'UE",
    "blogUrl": "/blog/2026-07-02-securite-routiere-hommes-majoritaires-mortalite-france-ue/",
    "date": "2026-07-02",
    "updatedAt": "2026-07-02T18:15:00.000Z"
  },
  {
    "claimId": "hommes-accidents-travail",
    "side": "hommes",
    "claimTitle": "Hommes toujours davantage touchés par les accidents du travail",
    "claimMetric": ">90 %",
    "blogTitle": "Sinistralité au travail : les accidents reconnus restent surtout masculins, les maladies professionnelles deviennent plus mixtes",
    "blogUrl": "/blog/2026-06-28-sinistralite-travail-femmes-hommes-france-europe/",
    "date": "2026-06-28",
    "updatedAt": "2026-06-28T18:40:00.000Z"
  },
  {
    "claimId": "hommes-esperance-vie-monde",
    "side": "hommes",
    "claimTitle": "Espérance de vie masculine plus courte dans presque tous les pays",
    "claimMetric": "quasi tous pays",
    "blogTitle": "Espérance de vie et années sans incapacité : l'écart femmes-hommes se resserre fortement quand on mesure la santé vécue",
    "blogUrl": "/blog/2026-06-28-esperance-vie-sans-incapacite-femmes-hommes-france-ue/",
    "date": "2026-06-28",
    "updatedAt": "2026-06-28T08:58:00.000Z"
  },
  {
    "claimId": "hommes-esperance-vie",
    "side": "hommes",
    "claimTitle": "Espérance de vie plus courte pour les hommes en France",
    "claimMetric": "-5,6 ans",
    "blogTitle": "Espérance de vie et années sans incapacité : l'écart femmes-hommes se resserre fortement quand on mesure la santé vécue",
    "blogUrl": "/blog/2026-06-28-esperance-vie-sans-incapacite-femmes-hommes-france-ue/",
    "date": "2026-06-28",
    "updatedAt": "2026-06-28T08:58:00.000Z"
  },
  {
    "claimId": "hommes-femme-principale-pourvoyeuse-satisfaction",
    "side": "hommes",
    "claimTitle": "Dans neuf pays, satisfaction déclarée plus basse quand la femme assure seule le revenu",
    "claimMetric": "pénalité de bien-être",
    "blogTitle": "Quand la femme gagne plus en France : séparation plus probable, insatisfaction non confirmée",
    "blogUrl": "/blog/2026-06-25-femme-gagne-plus-separation-satisfaction-france/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T15:55:00.000Z"
  }
] as const satisfies readonly HomeBlogUpdate[];
