// This file is generated by scripts/generate-seo.mjs. Do not edit by hand.
export type HomeBlogUpdate = {
  claimId: string;
  side: "hommes" | "femmes";
  claimTitle: string;
  claimMetric: string;
  blogTitle: string;
  blogUrl: string;
  date: string;
  updatedAt: string;
};

export const homeBlogUpdates = [
  {
    "claimId": "femmes-soin-non-remunere-emploi",
    "side": "femmes",
    "claimTitle": "Femmes tenues hors de l'emploi par le soin non rémunéré",
    "claimMetric": "708 M",
    "blogTitle": "Retraites : les écarts de pension se réduisent, mais les femmes âgées restent plus exposées à la pauvreté",
    "blogUrl": "/blog/2026-07-05-retraites-ecart-pension-pauvrete-femmes-hommes-france-ue-ocde/",
    "date": "2026-07-05",
    "updatedAt": "2026-07-05T07:30:00.000Z"
  },
  {
    "claimId": "femmes-ecart-salaire",
    "side": "femmes",
    "claimTitle": "Salaire inférieur pour une femme à profil comparable à un homme",
    "claimMetric": "3,0-4,8 %",
    "blogTitle": "Retraites : les écarts de pension se réduisent, mais les femmes âgées restent plus exposées à la pauvreté",
    "blogUrl": "/blog/2026-07-05-retraites-ecart-pension-pauvrete-femmes-hommes-france-ue-ocde/",
    "date": "2026-07-05",
    "updatedAt": "2026-07-05T07:30:00.000Z"
  },
  {
    "claimId": "femmes-temps-partiel",
    "side": "femmes",
    "claimTitle": "Temps partiel plus fréquent chez les femmes, lecture ambivalente",
    "claimMetric": "26,8 % vs 8,7 %",
    "blogTitle": "Retraites : les écarts de pension se réduisent, mais les femmes âgées restent plus exposées à la pauvreté",
    "blogUrl": "/blog/2026-07-05-retraites-ecart-pension-pauvrete-femmes-hommes-france-ue-ocde/",
    "date": "2026-07-05",
    "updatedAt": "2026-07-05T07:30:00.000Z"
  },
  {
    "claimId": "femmes-charge-domestique-soin",
    "side": "femmes",
    "claimTitle": "Femmes assumant beaucoup plus de soin non rémunéré",
    "claimMetric": "2,5x",
    "blogTitle": "Parentalité : l'emploi baisse surtout pour les mères, tandis que les pères gagnent du temps parental sans rattraper tout l'écart",
    "blogUrl": "/blog/2026-07-03-parentalite-emploi-meres-peres-enfants-france-ue-ocde/",
    "date": "2026-07-03",
    "updatedAt": "2026-07-03T18:30:00.000Z"
  },
  {
    "claimId": "hommes-conge-paternite-ocde",
    "side": "hommes",
    "claimTitle": "Pères limités par un congé paternité payé très court",
    "claimMetric": "2,4 sem.",
    "blogTitle": "Parentalité : l'emploi baisse surtout pour les mères, tandis que les pères gagnent du temps parental sans rattraper tout l'écart",
    "blogUrl": "/blog/2026-07-03-parentalite-emploi-meres-peres-enfants-france-ue-ocde/",
    "date": "2026-07-03",
    "updatedAt": "2026-07-03T18:30:00.000Z"
  },
  {
    "claimId": "hommes-accidents-route-monde",
    "side": "hommes",
    "claimTitle": "Hommes beaucoup plus exposés à la mortalité routière",
    "claimMetric": "3x",
    "blogTitle": "Sécurité routière : les hommes restent très majoritaires parmi les morts sur la route en France comme dans l'UE",
    "blogUrl": "/blog/2026-07-02-securite-routiere-hommes-majoritaires-mortalite-france-ue/",
    "date": "2026-07-02",
    "updatedAt": "2026-07-02T18:15:00.000Z"
  },
  {
    "claimId": "femmes-ingenierie",
    "side": "femmes",
    "claimTitle": "Femmes moins présentes dans l'ingénierie malgré une réussite scolaire élevée",
    "claimMetric": "24 %",
    "blogTitle": "IA générative au travail : les emplois féminisés sont plus exposés, mais les métiers du numérique restent surtout masculins",
    "blogUrl": "/blog/2026-07-01-ia-generative-emplois-feminises-numerique/",
    "date": "2026-07-01",
    "updatedAt": "2026-07-01T17:00:00.000Z"
  },
  {
    "claimId": "femmes-filles-hors-ecole",
    "side": "femmes",
    "claimTitle": "Enfants hors de l'école : estimations mondiales proches selon le sexe",
    "claimMetric": "133 M filles vs 140 M garçons",
    "blogTitle": "Sorties précoces d'études : les jeunes hommes restent plus exposés en Europe",
    "blogUrl": "/blog/2026-06-30-sorties-precoces-jeunes-hommes-europe-france/",
    "date": "2026-06-30",
    "updatedAt": "2026-06-30T07:30:00.000Z"
  },
  {
    "claimId": "hommes-decrochage-garcons-monde",
    "side": "hommes",
    "claimTitle": "Garçons massivement hors de l'école ou en redoublement",
    "claimMetric": "140 M",
    "blogTitle": "Sorties précoces d'études : les jeunes hommes restent plus exposés en Europe",
    "blogUrl": "/blog/2026-06-30-sorties-precoces-jeunes-hommes-europe-france/",
    "date": "2026-06-30",
    "updatedAt": "2026-06-30T07:30:00.000Z"
  },
  {
    "claimId": "hommes-sorties-precoces",
    "side": "hommes",
    "claimTitle": "Garçons plus touchés par les sorties précoces du système scolaire",
    "claimMetric": "9,5 % vs 5,6 %",
    "blogTitle": "Sorties précoces d'études : les jeunes hommes restent plus exposés en Europe",
    "blogUrl": "/blog/2026-06-30-sorties-precoces-jeunes-hommes-europe-france/",
    "date": "2026-06-30",
    "updatedAt": "2026-06-30T07:30:00.000Z"
  },
  {
    "claimId": "hommes-accidents-travail",
    "side": "hommes",
    "claimTitle": "Hommes très majoritaires parmi les morts au travail",
    "claimMetric": ">90 %",
    "blogTitle": "Sinistralité au travail : les accidents reconnus restent surtout masculins, les maladies professionnelles deviennent plus mixtes",
    "blogUrl": "/blog/2026-06-28-sinistralite-travail-femmes-hommes-france-europe/",
    "date": "2026-06-28",
    "updatedAt": "2026-06-28T18:40:00.000Z"
  },
  {
    "claimId": "hommes-esperance-vie-monde",
    "side": "hommes",
    "claimTitle": "Espérance de vie masculine plus courte dans presque tous les pays",
    "claimMetric": "quasi tous pays",
    "blogTitle": "Espérance de vie et années sans incapacité : l'écart femmes-hommes se resserre fortement quand on mesure la santé vécue",
    "blogUrl": "/blog/2026-06-28-esperance-vie-sans-incapacite-femmes-hommes-france-ue/",
    "date": "2026-06-28",
    "updatedAt": "2026-06-28T08:58:00.000Z"
  },
  {
    "claimId": "hommes-esperance-vie",
    "side": "hommes",
    "claimTitle": "Espérance de vie plus courte pour les hommes en France",
    "claimMetric": "-5,6 ans",
    "blogTitle": "Espérance de vie et années sans incapacité : l'écart femmes-hommes se resserre fortement quand on mesure la santé vécue",
    "blogUrl": "/blog/2026-06-28-esperance-vie-sans-incapacite-femmes-hommes-france-ue/",
    "date": "2026-06-28",
    "updatedAt": "2026-06-28T08:58:00.000Z"
  },
  {
    "claimId": "hommes-vocabulaire-masculinisme-pejoratif",
    "side": "hommes",
    "claimTitle": "Défense des hommes : pas de terme neutre stabilisé",
    "claimMetric": "mot manquant",
    "blogTitle": "Masculinisme et féminisme : une asymétrie de vocabulaire dans les dictionnaires",
    "blogUrl": "/blog/2026-06-25-masculinisme-feminisme-vocabulaire-asymetrie/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T21:05:00.000Z"
  },
  {
    "claimId": "hommes-bourses-stem-reservees-femmes",
    "side": "hommes",
    "claimTitle": "Hommes exclus de certaines bourses STEM réservées aux femmes",
    "claimMetric": "15 000 €",
    "blogTitle": "Enseignement supérieur : plus de diplômées, moins de STEM, et un écart d'emploi qui persiste",
    "blogUrl": "/blog/2026-06-25-superieur-stem-emploi-asymetries-sexe/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T18:30:00.000Z"
  },
  {
    "claimId": "hommes-femme-principale-pourvoyeuse-satisfaction",
    "side": "hommes",
    "claimTitle": "Quand la femme assure seule le revenu, la baisse de satisfaction est plus marquée chez les hommes",
    "claimMetric": "pénalité de bien-être",
    "blogTitle": "Quand la femme gagne plus en France : séparation plus probable, insatisfaction non confirmée",
    "blogUrl": "/blog/2026-06-25-femme-gagne-plus-separation-satisfaction-france/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T15:55:00.000Z"
  },
  {
    "claimId": "hommes-suicide-monde",
    "side": "hommes",
    "claimTitle": "Hommes beaucoup plus exposés à la mort par suicide",
    "claimMetric": ">2x",
    "blogTitle": "Suicide et gestes auto-infligés : deux asymétries de sexe à lire séparément en 2026",
    "blogUrl": "/blog/2026-06-25-suicide-gestes-auto-infliges-asymetries-sexe/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T06:30:00.000Z"
  },
  {
    "claimId": "hommes-suicide",
    "side": "hommes",
    "claimTitle": "Surmortalité masculine par suicide",
    "claimMetric": "75 %",
    "blogTitle": "Suicide et gestes auto-infligés : deux asymétries de sexe à lire séparément en 2026",
    "blogUrl": "/blog/2026-06-25-suicide-gestes-auto-infliges-asymetries-sexe/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T06:30:00.000Z"
  }
] as const satisfies readonly HomeBlogUpdate[];
