// This file is generated by scripts/generate-seo.mjs. Do not edit by hand.
export type HomeBlogUpdate = {
  claimId: string;
  side: "hommes" | "femmes";
  claimTitle: string;
  claimMetric: string;
  blogTitle: string;
  blogUrl: string;
  date: string;
  updatedAt: string;
};

export const homeBlogUpdates = [
  {
    "claimId": "hommes-vocabulaire-masculinisme-pejoratif",
    "side": "hommes",
    "claimTitle": "Masculinisme défini surtout par ses usages péjoratifs",
    "claimMetric": "mot péjoratif",
    "blogTitle": "Masculinisme et féminisme : une asymétrie de vocabulaire dans les dictionnaires",
    "blogUrl": "/blog/2026-06-25-masculinisme-feminisme-vocabulaire-asymetrie/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T21:05:00.000Z"
  },
  {
    "claimId": "femmes-ingenierie",
    "side": "femmes",
    "claimTitle": "Femmes moins présentes dans l'ingénierie malgré une réussite scolaire élevée",
    "claimMetric": "24 %",
    "blogTitle": "Enseignement supérieur : plus de diplômées, moins de STEM, et un écart d'emploi qui persiste",
    "blogUrl": "/blog/2026-06-25-superieur-stem-emploi-asymetries-sexe/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T18:30:00.000Z"
  },
  {
    "claimId": "hommes-bourses-stem-reservees-femmes",
    "side": "hommes",
    "claimTitle": "Hommes exclus de certaines bourses STEM réservées aux femmes",
    "claimMetric": "15 000 €",
    "blogTitle": "Enseignement supérieur : plus de diplômées, moins de STEM, et un écart d'emploi qui persiste",
    "blogUrl": "/blog/2026-06-25-superieur-stem-emploi-asymetries-sexe/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T18:30:00.000Z"
  },
  {
    "claimId": "hommes-femme-principale-pourvoyeuse-satisfaction",
    "side": "hommes",
    "claimTitle": "Quand la femme assure seule le revenu, la baisse de satisfaction est plus marquée chez les hommes",
    "claimMetric": "pénalité de bien-être",
    "blogTitle": "Quand la femme gagne plus en France : séparation plus probable, insatisfaction non confirmée",
    "blogUrl": "/blog/2026-06-25-femme-gagne-plus-separation-satisfaction-france/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T15:55:00.000Z"
  },
  {
    "claimId": "hommes-suicide-monde",
    "side": "hommes",
    "claimTitle": "Hommes beaucoup plus exposés à la mort par suicide",
    "claimMetric": ">2x",
    "blogTitle": "Suicide et gestes auto-infligés : deux asymétries de sexe à lire séparément en 2026",
    "blogUrl": "/blog/2026-06-25-suicide-gestes-auto-infliges-asymetries-sexe/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T06:30:00.000Z"
  },
  {
    "claimId": "hommes-suicide",
    "side": "hommes",
    "claimTitle": "Surmortalité masculine par suicide",
    "claimMetric": "75 %",
    "blogTitle": "Suicide et gestes auto-infligés : deux asymétries de sexe à lire séparément en 2026",
    "blogUrl": "/blog/2026-06-25-suicide-gestes-auto-infliges-asymetries-sexe/",
    "date": "2026-06-25",
    "updatedAt": "2026-06-25T06:30:00.000Z"
  }
] as const satisfies readonly HomeBlogUpdate[];
